/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppDisponibilidadeRouteImport } from './routes/_app/disponibilidade'
import { Route as AppLinkRouteImport } from './routes/_app/link'
import { Route as AppServicosRouteImport } from './routes/_app/servicos'
import { Route as ASlugRouteImport } from './routes/a.$slug'
import { Route as AgendamentoTokenRouteImport } from './routes/agendamento.$token'
import { Route as ApiCalendarioTokenRouteImport } from './routes/api/calendario/$token'
import { Route as ApiCronLembretesRouteImport } from './routes/api/cron/lembretes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDisponibilidadeRoute = AppDisponibilidadeRouteImport.update({
  id: '/disponibilidade',
  path: '/disponibilidade',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLinkRoute = AppLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServicosRoute = AppServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AppRouteRoute,
} as any)
const ASlugRoute = ASlugRouteImport.update({
  id: '/a/$slug',
  path: '/a/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoTokenRoute = AgendamentoTokenRouteImport.update({
  id: '/agendamento/$token',
  path: '/agendamento/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarioTokenRoute = ApiCalendarioTokenRouteImport.update({
  id: '/api/calendario/$token',
  path: '/api/calendario/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronLembretesRoute = ApiCronLembretesRouteImport.update({
  id: '/api/cron/lembretes',
  path: '/api/cron/lembretes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AppAgendaRoute
  '/disponibilidade': typeof AppDisponibilidadeRoute
  '/link': typeof AppLinkRoute
  '/servicos': typeof AppServicosRoute
  '/a/$slug': typeof ASlugRoute
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/api/calendario/$token': typeof ApiCalendarioTokenRoute
  '/api/cron/lembretes': typeof ApiCronLembretesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AppAgendaRoute
  '/disponibilidade': typeof AppDisponibilidadeRoute
  '/link': typeof AppLinkRoute
  '/servicos': typeof AppServicosRoute
  '/a/$slug': typeof ASlugRoute
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/api/calendario/$token': typeof ApiCalendarioTokenRoute
  '/api/cron/lembretes': typeof ApiCronLembretesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/disponibilidade': typeof AppDisponibilidadeRoute
  '/_app/link': typeof AppLinkRoute
  '/_app/servicos': typeof AppServicosRoute
  '/a/$slug': typeof ASlugRoute
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/api/calendario/$token': typeof ApiCalendarioTokenRoute
  '/api/cron/lembretes': typeof ApiCronLembretesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/disponibilidade'
    | '/link'
    | '/servicos'
    | '/a/$slug'
    | '/agendamento/$token'
    | '/api/calendario/$token'
    | '/api/cron/lembretes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/disponibilidade'
    | '/link'
    | '/servicos'
    | '/a/$slug'
    | '/agendamento/$token'
    | '/api/calendario/$token'
    | '/api/cron/lembretes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/agenda'
    | '/_app/disponibilidade'
    | '/_app/link'
    | '/_app/servicos'
    | '/a/$slug'
    | '/agendamento/$token'
    | '/api/calendario/$token'
    | '/api/cron/lembretes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ASlugRoute: typeof ASlugRoute
  AgendamentoTokenRoute: typeof AgendamentoTokenRoute
  ApiCalendarioTokenRoute: typeof ApiCalendarioTokenRoute
  ApiCronLembretesRoute: typeof ApiCronLembretesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/disponibilidade': {
      id: '/_app/disponibilidade'
      path: '/disponibilidade'
      fullPath: '/disponibilidade'
      preLoaderRoute: typeof AppDisponibilidadeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/link': {
      id: '/_app/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof AppLinkRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/servicos': {
      id: '/_app/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AppServicosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/a/$slug': {
      id: '/a/$slug'
      path: '/a/$slug'
      fullPath: '/a/$slug'
      preLoaderRoute: typeof ASlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento/$token': {
      id: '/agendamento/$token'
      path: '/agendamento/$token'
      fullPath: '/agendamento/$token'
      preLoaderRoute: typeof AgendamentoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendario/$token': {
      id: '/api/calendario/$token'
      path: '/api/calendario/$token'
      fullPath: '/api/calendario/$token'
      preLoaderRoute: typeof ApiCalendarioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/lembretes': {
      id: '/api/cron/lembretes'
      path: '/api/cron/lembretes'
      fullPath: '/api/cron/lembretes'
      preLoaderRoute: typeof ApiCronLembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppDisponibilidadeRoute: typeof AppDisponibilidadeRoute
  AppLinkRoute: typeof AppLinkRoute
  AppServicosRoute: typeof AppServicosRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppDisponibilidadeRoute: AppDisponibilidadeRoute,
  AppLinkRoute: AppLinkRoute,
  AppServicosRoute: AppServicosRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ASlugRoute: ASlugRoute,
  AgendamentoTokenRoute: AgendamentoTokenRoute,
  ApiCalendarioTokenRoute: ApiCalendarioTokenRoute,
  ApiCronLembretesRoute: ApiCronLembretesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
